[tool.nx]
autoActivate = true

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.12"

[build-system]
requires = ["poetry-core==1.1.0"]
build-backend = "poetry.core.masonry.api"
